# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41861114b690ad3ee4c1804c340dcc5a31aef8c4e334ec859bb44a04757e8b1e8a33eb2de4922982dd85920401252ada59f1a68b1fcb1b15cfcb3358fdde134f

test:
  secret_key_base: a73167784d5ed76cff81ecb8439387e5aa17a04a29566407d84b8be4fd9f176e4c9fe1d9fa9b10a2942c71cbb40a6f5c27a89155cb3a96182591a3f6bd37a818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
